
get http://localhost:8888/.netlify/functions/hello

###

post http://localhost:8888/.netlify/functions/addsource
Content-Type: application/json

{
   "sourceID":"0",
   "type":"solar",
   "displayName":"☀️ Solar",
   "$/kWh":10.2,
   "cm3CO2/h":0.2
}


###

get http://localhost:8888/.netlify/functions/findbyidentifier

###

get http://localhost:8888/.netlify/functions/findallsources

###

get http://localhost:8888/.netlify/functions/getuserwhconsumption